name: DeluxeCoinflip
version: '${version}'
main: net.zithium.deluxecoinflip.DeluxeCoinflipPlugin
authors: [ ItsLewizzz, ItzSave, ItsSimplyLeo, hyperion ]
api-version: 1.21

softdepend:
  - PlaceholderAPI
  - Vault
  - TokenEnchant
  - TokenManager
  - EssentialsX
  - LeaderOS
  - CoinsEngine

permissions:
  coinflip.admin:
    default: op
